version: "{build}"
build: off
shallow_clone: true
skip_tags: true

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "1"

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g i tape
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test
